apiVersion: v1
kind: Pod
metadata: 
  name: vating-app-pod
  labels:
    name: vating-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: vating-app-pod
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
        